fix: To prep for release 1.1.0 (#122)
* deps: bump to latest idb-connector for node 18 support

* build: Update deps for security

* chore: Update CHANGELOG

* test: Use instanceof to workaround issue

With node 14+ the following test cases fail:

  1) Connection Class Tests
       connect
         connects to *LOCAL when no params passed:
     AssertionError: expected {} to be a dbconn

  2) Connection Class Tests
       connect
         connects with passed db, user, password params:
     AssertionError: expected {} to be a dbconn

  3) Connection Class Tests
       getStatement
         should return a new statement initialized with the the dbconn:
     AssertionError: expected {} to be a dbstmt

changing to use instanceof fixes these up.